name: C Program CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C compiler
      run: sudo apt-get install -y gcc

    - name: Build repeat program
      run: make

    - name: Test repeat program
      run: |
        ./repeat "echo Hello, world!" -n5
